### PR TITLE
Remove preview directory

### PR DESCRIPTION
**Pull request by wcheng-msft**
rename -- remove preview directory. Fix up associated project files that used relative paths to remove one directory (..\)

ClickOnceWrapper had a problem, in that its dependson was pre-run instead of pre-build, which means it had to have run successfully already; this was fixed.

update README.md to reference paths without preview.

### CODE REVIEW

**Comment by JohnMcPMS** [comment]
Update CODEOWNERS for path change as well.

**Comment by JohnMcPMS** [comment]
Also, the root README seems like it should have a more prominent mention of the MsixCore directory.  At least a link to MsixCore\README.md somewhere near the top.

---
In reply to: [564745029](https://github.com/Microsoft/msix-packaging/pull/292#issuecomment-564745029) [](ancestors = 564745029)

**Comment by wcheng-msft** [comment]
> Update CODEOWNERS for path change as well.

ah, that's why you guys were added. updated.

**Comment by wcheng-msft** [comment]
> Also, the root README seems like it should have a more prominent mention of the MsixCore directory.  At least a link to MsixCore\README.md somewhere near the top.
> 
> In reply to: 564745029 [](ancestors = 564745029)

added a sentence and a link.

**Pull request merged**
